---
- hosts: servers
  remote_user: "{{ remote_user }}"
  become: True
  roles:
    - init
    - firewalld
    - nginx
    - php
    - mysql
    - laravel
    - nodejs
    - nuxt
    - { role: elasticsearch, when: install_Elasticsearch == "yes" }
    - { role: mroonga, when: install_mroonga == "yes" }